### ISSUE TITLE
Test runner hangs and is killed

### ISSUE THREAD

**Issue by xqb64** [nlsandler/writing-a-c-compiler-tests#83] opened 2024-10-01 23:26 UTC
I'm working my way through the book.  I'm at chapter 19, and I was about to test whether propagating copies works for part 2.  I'm writing in Rust (so I doubt I have a leak somewhere).

```
alex@smartalex-pc:~/Repositories/ucc$ ./tests/test_compiler target/release/ucc --chapter 19 --propagate-copies
Killed
alex@smartalex-pc:~/Repositories/ucc$ ./tests/test_compiler target/release/ucc --chapter 19
Killed
alex@smartalex-pc:~/Repositories/ucc$ ./tests/test_compiler target/release/ucc --chapter 19 --propagate-copies --int-only
----------------------------------------------------------------------
Ran 379 tests in 15.456s

OK
alex@smartalex-pc:~/Repositories/ucc$ ./tests/test_compiler target/release/ucc --chapter 18
----------------------------------------------------------------------
Ran 946 tests in 36.618s

OK
```

I have no way of figuring out what's going wrong and where.
I tried running each test file individually (automated it), and everything terminated, none of them hanged.

**Comment by nlsandler** [comment] 2024-10-02 18:42
Thanks for reporting this! A few follow-up questions to help repo this:

1. What platform are you on?
2. Make sure the test suite is up-to-date, then try this command:
`./tests/test_compiler target/release/ucc --chapter 19 --propagate-copies --latest-only -vv`

  The `-vv` option should show us which test it's hanging on and `--latest-only` will skip the chapter 1-18 tests.

3. Could you share the script or command you used to run each test individually? Maybe there's a discrepancy between that and what `test_compiler` is doing.

**Comment by nlsandler** [comment] 2024-10-21 18:16
@xqb64 did you ever get this resolved?

**Comment by xqb64** [comment] 2024-10-21 23:28
@nlsandler Yes.  I'm done with the book.  Unfortunately, I can't reproduce the issue anymore.  I might have a hint for you, though.  If I remember, when I deleted all dbg! and println! statements, I was able to proceed.  However, this is just a hunch and not hard evidence, so take it with a grain of salt.  I'm sorry that I can't help further when it comes to this issue.

**Comment by nlsandler** [comment] 2024-10-22 16:35
Thanks for the extra details, and I'm glad you eventually managed to get it fixed. I'm going to close this as can't reproduce, but if anyone else runs into it hopefully your report will help us get to the bottom of it.

**Closed by nlsandler** 2024-10-22 16:35 UTC
