### ISSUE TITLE
Missing test: function declaration with missing parameter name

### ISSUE THREAD

**Issue by meithecatte** [nlsandler/writing-a-c-compiler-tests#30] opened 2024-05-27 19:05 UTC
As far as I can see, there is no test for the constraint that disallows `void f(int) {}` (C11 6.9.1.5). This in itself is understandable, as I believe this becomes legal in C23.

However, one thing that definitely should be tested is the following valid declaration:
```
int f(int);
```

This is because parameter names are, in all versions of the standard, optional within function *declarations*.

(I noticed this because I implemented a check for C11 6.9.1.5 in the part of the code that also looks at declarations, and didn't get a test failure)

**Comment by meithecatte** [comment] 2024-05-27 19:13
In particular, one edgecase here is declarations where parameters with and without name are intermixed.

**Comment by nlsandler** [comment] 2024-05-28 22:10
This was by design; function declarations without parameter names are out of scope for this project (just for the sake of reducing the total number of edge cases readers have to handle).

That said, even though the valid test case `int f(int);` is outside the scope of the project, we could still include invalid test cases to disallow `int f(int) {return 0;}` and `int f(int a, int){return 0;}`, since those are invalid regardless.

**Comment by nlsandler** [comment] 2024-05-28 22:18
On second thought, I'm not going to add those invalid test cases since, as you pointed out, they become legal in C23.
I'm closing this as wontfix, but feel free to reopen if I've misunderstood anything.

**Closed by nlsandler** 2024-05-28 22:18 UTC
Labels: wontfix
